# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.setEnabled(True)
        widget.resize(811, 480)
        widget.setMinimumSize(QtCore.QSize(811, 480))
        widget.setMaximumSize(QtCore.QSize(811, 480))
        self.topbar = QtWidgets.QFrame(widget)
        self.topbar.setGeometry(QtCore.QRect(0, 0, 811, 71))
        self.topbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topbar.setObjectName("topbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topbar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_help = QtWidgets.QPushButton(self.topbar)
        self.btn_help.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_help.sizePolicy().hasHeightForWidth())
        self.btn_help.setSizePolicy(sizePolicy)
        self.btn_help.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_help.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_help.setSizeIncrement(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.btn_help.setFont(font)
        self.btn_help.setStyleSheet("border: 2px solid black;\n"
"border-radius: 6px;\n"
"background-color: white;")
        self.btn_help.setObjectName("btn_help")
        self.horizontalLayout.addWidget(self.btn_help)
        self.label_current_people = QtWidgets.QLabel(self.topbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_current_people.sizePolicy().hasHeightForWidth())
        self.label_current_people.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(24)
        self.label_current_people.setFont(font)
        self.label_current_people.setObjectName("label_current_people")
        self.horizontalLayout.addWidget(self.label_current_people)
        self.label_date_time = QtWidgets.QLabel(self.topbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_date_time.sizePolicy().hasHeightForWidth())
        self.label_date_time.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(24)
        self.label_date_time.setFont(font)
        self.label_date_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_date_time.setObjectName("label_date_time")
        self.horizontalLayout.addWidget(self.label_date_time)
        self.layoutWidget = QtWidgets.QWidget(widget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 140, 691, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_main_title = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(48)
        self.label_main_title.setFont(font)
        self.label_main_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main_title.setObjectName("label_main_title")
        self.verticalLayout.addWidget(self.label_main_title)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_check_in_out = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_check_in_out.setMinimumSize(QtCore.QSize(200, 100))
        self.btn_check_in_out.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(36)
        self.btn_check_in_out.setFont(font)
        self.btn_check_in_out.setStyleSheet("border: 2px solid black;\n"
"border-radius: 6px;\n"
"background-color: white;")
        self.btn_check_in_out.setObjectName("btn_check_in_out")
        self.horizontalLayout_2.addWidget(self.btn_check_in_out)
        self.btn_going_out = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_going_out.setMinimumSize(QtCore.QSize(200, 100))
        self.btn_going_out.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(36)
        self.btn_going_out.setFont(font)
        self.btn_going_out.setStyleSheet("border: 2px solid black;\n"
"border-radius: 6px;\n"
"background-color: white;")
        self.btn_going_out.setObjectName("btn_going_out")
        self.horizontalLayout_2.addWidget(self.btn_going_out)
        self.btn_fingerprint = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_fingerprint.setMinimumSize(QtCore.QSize(200, 100))
        self.btn_fingerprint.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(36)
        self.btn_fingerprint.setFont(font)
        self.btn_fingerprint.setStyleSheet("border: 2px solid black;\n"
"border-radius: 6px;\n"
"background-color: white;")
        self.btn_fingerprint.setObjectName("btn_fingerprint")
        self.horizontalLayout_2.addWidget(self.btn_fingerprint)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.btn_help.setText(_translate("widget", "❓"))
        self.label_current_people.setText(_translate("widget", "현재 재실 인원 : 0명"))
        self.label_date_time.setText(_translate("widget", "Fri May 16  10:06PM"))
        self.label_main_title.setText(_translate("widget", "🔽 원하는 항목을 선택해주세요."))
        self.btn_check_in_out.setText(_translate("widget", "등하교"))
        self.btn_going_out.setText(_translate("widget", "외출"))
        self.btn_fingerprint.setText(_translate("widget", "지문 등록"))
