# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.setEnabled(True)
        widget.resize(811, 480)
        widget.setMinimumSize(QtCore.QSize(811, 480))
        widget.setMaximumSize(QtCore.QSize(811, 480))
        widget.setStyleSheet("QWidget {\n"
"    background-color: #f0faff\n"
"\n"
";  /* 부드러운 에그쉘 색 */\n"
"}")
        self.topbar = QtWidgets.QFrame(widget)
        self.topbar.setGeometry(QtCore.QRect(0, 0, 811, 81))
        self.topbar.setStyleSheet("QFrame {\n"
"    background-color: #fefbf6; /* 전체 배경과 통일감 있게 */\n"
"    border: 2px solid #e0e0e0; /* 아주 연한 회색 테두리 */\n"
"    border-radius: 12px;        /* 살짝 둥근 모서리 */\n"
"    padding: 6px;\n"
"}")
        self.topbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topbar.setObjectName("topbar")
        self.label_date_time = QtWidgets.QLabel(self.topbar)
        self.label_date_time.setGeometry(QtCore.QRect(520, 20, 280, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_date_time.sizePolicy().hasHeightForWidth())
        self.label_date_time.setSizePolicy(sizePolicy)
        self.label_date_time.setMinimumSize(QtCore.QSize(280, 42))
        self.label_date_time.setMaximumSize(QtCore.QSize(280, 16777215))
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(24)
        self.label_date_time.setFont(font)
        self.label_date_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_date_time.setObjectName("label_date_time")
        self.label_current_people = QtWidgets.QLabel(self.topbar)
        self.label_current_people.setGeometry(QtCore.QRect(70, 20, 204, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_current_people.sizePolicy().hasHeightForWidth())
        self.label_current_people.setSizePolicy(sizePolicy)
        self.label_current_people.setMinimumSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(24)
        self.label_current_people.setFont(font)
        self.label_current_people.setObjectName("label_current_people")
        self.btn_help = QtWidgets.QPushButton(self.topbar)
        self.btn_help.setEnabled(True)
        self.btn_help.setGeometry(QtCore.QRect(14, 20, 40, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_help.sizePolicy().hasHeightForWidth())
        self.btn_help.setSizePolicy(sizePolicy)
        self.btn_help.setMinimumSize(QtCore.QSize(40, 42))
        self.btn_help.setMaximumSize(QtCore.QSize(40, 42))
        self.btn_help.setSizeIncrement(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.btn_help.setFont(font)
        self.btn_help.setStyleSheet("border: 2px solid black;\n"
"border-radius: 6px;\n"
"background-color: white;")
        self.btn_help.setObjectName("btn_help")
        self.layoutWidget = QtWidgets.QWidget(widget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 140, 691, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_main_title = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(48)
        self.label_main_title.setFont(font)
        self.label_main_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main_title.setObjectName("label_main_title")
        self.verticalLayout.addWidget(self.label_main_title)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_check_in_out = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_check_in_out.setMinimumSize(QtCore.QSize(200, 100))
        self.btn_check_in_out.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_check_in_out.setFont(font)
        self.btn_check_in_out.setStyleSheet("QPushButton {\n"
"    background-color: #fefbf6;\n"
"    border: 1.5px solid #e0e0e0;\n"
"    border-radius: 15px;\n"
"    padding: 10px 20px;\n"
"    font-size: 36px;\n"
"    font-weight: bold;\n"
"    color: #333333;\n"
"}")
        self.btn_check_in_out.setObjectName("btn_check_in_out")
        self.horizontalLayout_2.addWidget(self.btn_check_in_out)
        self.btn_going_out = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_going_out.setMinimumSize(QtCore.QSize(200, 100))
        self.btn_going_out.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_going_out.setFont(font)
        self.btn_going_out.setStyleSheet("QPushButton {\n"
"    background-color: #fefbf6;\n"
"    border: 1.5px solid #e0e0e0;\n"
"    border-radius: 15px;\n"
"    padding: 10px 20px;\n"
"    font-size: 36px;\n"
"    font-weight: bold;\n"
"    color: #333333;\n"
"}")
        self.btn_going_out.setObjectName("btn_going_out")
        self.horizontalLayout_2.addWidget(self.btn_going_out)
        self.btn_fingerprint = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_fingerprint.setMinimumSize(QtCore.QSize(200, 100))
        self.btn_fingerprint.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_fingerprint.setFont(font)
        self.btn_fingerprint.setStyleSheet("QPushButton {\n"
"    background-color: #fefbf6;\n"
"    border: 1.5px solid #e0e0e0;\n"
"    border-radius: 15px;\n"
"    padding: 10px 20px;\n"
"    font-size: 36px;\n"
"    font-weight: bold;\n"
"    color: #333333;\n"
"}")
        self.btn_fingerprint.setObjectName("btn_fingerprint")
        self.horizontalLayout_2.addWidget(self.btn_fingerprint)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.label_date_time.setText(_translate("widget", "Fri May 16  10:06PM"))
        self.label_current_people.setText(_translate("widget", "현재 재실 인원 : 0명"))
        self.btn_help.setText(_translate("widget", "❓"))
        self.label_main_title.setText(_translate("widget", "🔽 원하는 항목을 선택해주세요."))
        self.btn_check_in_out.setText(_translate("widget", "등하교"))
        self.btn_going_out.setText(_translate("widget", "외출"))
        self.btn_fingerprint.setText(_translate("widget", "지문 등록"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QWidget()
    ui = Ui_widget()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())
