# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'check_in_out.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(811, 480)
        Form.setMinimumSize(QtCore.QSize(811, 480))
        Form.setMaximumSize(QtCore.QSize(811, 480))
        Form.setStyleSheet("QWidget {\n"
"    background-color: #f0faff\n"
"\n"
";  /* 부드러운 에그쉘 색 */\n"
"}")
        self.inandout_title = QtWidgets.QLabel(Form)
        self.inandout_title.setGeometry(QtCore.QRect(20, 100, 120, 50))
        self.inandout_title.setMinimumSize(QtCore.QSize(120, 50))
        self.inandout_title.setMaximumSize(QtCore.QSize(90, 50))
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(36)
        self.inandout_title.setFont(font)
        self.inandout_title.setObjectName("inandout_title")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 150, 791, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_main_title = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(48)
        self.label_main_title.setFont(font)
        self.label_main_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main_title.setObjectName("label_main_title")
        self.verticalLayout.addWidget(self.label_main_title)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_check_in = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_check_in.setMinimumSize(QtCore.QSize(200, 100))
        self.btn_check_in.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_check_in.setFont(font)
        self.btn_check_in.setStyleSheet("QPushButton {\n"
"    background-color: #fefbf6;\n"
"    border: 1.5px solid #e0e0e0;\n"
"    border-radius: 15px;\n"
"    padding: 10px 20px;\n"
"    font-size: 36px;\n"
"    font-weight: bold;\n"
"    color: #333333;\n"
"}")
        self.btn_check_in.setObjectName("btn_check_in")
        self.horizontalLayout_2.addWidget(self.btn_check_in)
        self.btn_check_out = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_check_out.setMinimumSize(QtCore.QSize(200, 100))
        self.btn_check_out.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_check_out.setFont(font)
        self.btn_check_out.setStyleSheet("QPushButton {\n"
"    background-color: #fefbf6;\n"
"    border: 1.5px solid #e0e0e0;\n"
"    border-radius: 15px;\n"
"    padding: 10px 20px;\n"
"    font-size: 36px;\n"
"    font-weight: bold;\n"
"    color: #333333;\n"
"}")
        self.btn_check_out.setObjectName("btn_check_out")
        self.horizontalLayout_2.addWidget(self.btn_check_out)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_message = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_message.sizePolicy().hasHeightForWidth())
        self.label_message.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(40)
        self.label_message.setFont(font)
        self.label_message.setAlignment(QtCore.Qt.AlignCenter)
        self.label_message.setObjectName("label_message")
        self.verticalLayout.addWidget(self.label_message)
        self.topbar = QtWidgets.QFrame(Form)
        self.topbar.setGeometry(QtCore.QRect(0, 0, 811, 81))
        self.topbar.setStyleSheet("QFrame {\n"
"    background-color: #fefbf6; /* 전체 배경과 통일감 있게 */\n"
"    border: 2px solid #e0e0e0; /* 아주 연한 회색 테두리 */\n"
"    border-radius: 12px;        /* 살짝 둥근 모서리 */\n"
"    padding: 6px;\n"
"}")
        self.topbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topbar.setObjectName("topbar")
        self.btn_help = QtWidgets.QPushButton(self.topbar)
        self.btn_help.setEnabled(True)
        self.btn_help.setGeometry(QtCore.QRect(14, 20, 40, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_help.sizePolicy().hasHeightForWidth())
        self.btn_help.setSizePolicy(sizePolicy)
        self.btn_help.setMinimumSize(QtCore.QSize(40, 42))
        self.btn_help.setMaximumSize(QtCore.QSize(40, 42))
        self.btn_help.setSizeIncrement(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.btn_help.setFont(font)
        self.btn_help.setStyleSheet("border: 2px solid black;\n"
"border-radius: 6px;\n"
"background-color: white;")
        self.btn_help.setObjectName("btn_help")
        self.label_current_people = QtWidgets.QLabel(self.topbar)
        self.label_current_people.setGeometry(QtCore.QRect(70, 20, 204, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_current_people.sizePolicy().hasHeightForWidth())
        self.label_current_people.setSizePolicy(sizePolicy)
        self.label_current_people.setMinimumSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(24)
        self.label_current_people.setFont(font)
        self.label_current_people.setObjectName("label_current_people")
        self.label_date_time = QtWidgets.QLabel(self.topbar)
        self.label_date_time.setGeometry(QtCore.QRect(520, 20, 280, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_date_time.sizePolicy().hasHeightForWidth())
        self.label_date_time.setSizePolicy(sizePolicy)
        self.label_date_time.setMinimumSize(QtCore.QSize(280, 42))
        self.label_date_time.setMaximumSize(QtCore.QSize(280, 16777215))
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(24)
        self.label_date_time.setFont(font)
        self.label_date_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_date_time.setObjectName("label_date_time")
        self.btn_previous_page = QtWidgets.QPushButton(self.topbar)
        self.btn_previous_page.setEnabled(True)
        self.btn_previous_page.setGeometry(QtCore.QRect(430, 20, 70, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_previous_page.sizePolicy().hasHeightForWidth())
        self.btn_previous_page.setSizePolicy(sizePolicy)
        self.btn_previous_page.setMinimumSize(QtCore.QSize(70, 42))
        self.btn_previous_page.setMaximumSize(QtCore.QSize(70, 42))
        self.btn_previous_page.setSizeIncrement(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(36)
        self.btn_previous_page.setFont(font)
        self.btn_previous_page.setStyleSheet("border: 2px solid black;\n"
"border-radius: 6px;\n"
"background-color: white;")
        self.btn_previous_page.setObjectName("btn_previous_page")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.inandout_title.setText(_translate("Form", "등하교🎒 "))
        self.label_main_title.setText(_translate("Form", "🔽 원하는 항목을 선택해주세요."))
        self.btn_check_in.setText(_translate("Form", "등교"))
        self.btn_check_out.setText(_translate("Form", "하교"))
        self.label_message.setText(_translate("Form", "<                              \'메시지\'                              >"))
        self.btn_help.setText(_translate("Form", "❓"))
        self.label_current_people.setText(_translate("Form", "현재 재실 인원 : 0명"))
        self.label_date_time.setText(_translate("Form", "2025년 05월 19일 / 22:07분"))
        self.btn_previous_page.setText(_translate("Form", "↩"))
