# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'close.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.setEnabled(True)
        widget.resize(811, 480)
        widget.setMinimumSize(QtCore.QSize(811, 480))
        widget.setMaximumSize(QtCore.QSize(811, 480))
        widget.setStyleSheet("QWidget {\n"
"    background-color: #f0faff\n"
"\n"
";  /* 부드러운 에그쉘 색 */\n"
"}")
        self.topbar = QtWidgets.QFrame(widget)
        self.topbar.setGeometry(QtCore.QRect(0, 0, 811, 81))
        self.topbar.setStyleSheet("QFrame {\n"
"    background-color: #fefbf6; /* 전체 배경과 통일감 있게 */\n"
"    border: 2px solid #e0e0e0; /* 아주 연한 회색 테두리 */\n"
"    border-radius: 12px;        /* 살짝 둥근 모서리 */\n"
"    padding: 6px;\n"
"}")
        self.topbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topbar.setObjectName("topbar")
        self.label_date_time = QtWidgets.QLabel(self.topbar)
        self.label_date_time.setGeometry(QtCore.QRect(520, 20, 280, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_date_time.sizePolicy().hasHeightForWidth())
        self.label_date_time.setSizePolicy(sizePolicy)
        self.label_date_time.setMinimumSize(QtCore.QSize(280, 42))
        self.label_date_time.setMaximumSize(QtCore.QSize(280, 16777215))
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(24)
        self.label_date_time.setFont(font)
        self.label_date_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_date_time.setObjectName("label_date_time")
        self.label_current_people = QtWidgets.QLabel(self.topbar)
        self.label_current_people.setGeometry(QtCore.QRect(70, 20, 204, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_current_people.sizePolicy().hasHeightForWidth())
        self.label_current_people.setSizePolicy(sizePolicy)
        self.label_current_people.setMinimumSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(24)
        self.label_current_people.setFont(font)
        self.label_current_people.setObjectName("label_current_people")
        self.btn_help = QtWidgets.QPushButton(self.topbar)
        self.btn_help.setEnabled(True)
        self.btn_help.setGeometry(QtCore.QRect(14, 20, 40, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_help.sizePolicy().hasHeightForWidth())
        self.btn_help.setSizePolicy(sizePolicy)
        self.btn_help.setMinimumSize(QtCore.QSize(40, 42))
        self.btn_help.setMaximumSize(QtCore.QSize(40, 42))
        self.btn_help.setSizeIncrement(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.btn_help.setFont(font)
        self.btn_help.setStyleSheet("border: 2px solid black;\n"
"border-radius: 6px;\n"
"background-color: white;")
        self.btn_help.setObjectName("btn_help")
        self.btn_previous_page = QtWidgets.QPushButton(self.topbar)
        self.btn_previous_page.setEnabled(True)
        self.btn_previous_page.setGeometry(QtCore.QRect(440, 20, 70, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_previous_page.sizePolicy().hasHeightForWidth())
        self.btn_previous_page.setSizePolicy(sizePolicy)
        self.btn_previous_page.setMinimumSize(QtCore.QSize(70, 42))
        self.btn_previous_page.setMaximumSize(QtCore.QSize(70, 42))
        self.btn_previous_page.setSizeIncrement(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(36)
        self.btn_previous_page.setFont(font)
        self.btn_previous_page.setStyleSheet("border: 2px solid black;\n"
"border-radius: 6px;\n"
"background-color: white;")
        self.btn_previous_page.setObjectName("btn_previous_page")
        self.layoutWidget = QtWidgets.QWidget(widget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 140, 691, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_main_title = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(48)
        self.label_main_title.setFont(font)
        self.label_main_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main_title.setObjectName("label_main_title")
        self.verticalLayout.addWidget(self.label_main_title)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_yes = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_yes.setMinimumSize(QtCore.QSize(200, 100))
        self.btn_yes.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_yes.setFont(font)
        self.btn_yes.setStyleSheet("QPushButton {\n"
"    background-color: #fefbf6;\n"
"    border: 1.5px solid #e0e0e0;\n"
"    border-radius: 15px;\n"
"    padding: 10px 20px;\n"
"    font-size: 36px;\n"
"    font-weight: bold;\n"
"    color: #333333;\n"
"}")
        self.btn_yes.setObjectName("btn_yes")
        self.horizontalLayout_2.addWidget(self.btn_yes)
        self.btn_no = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_no.setMinimumSize(QtCore.QSize(200, 100))
        self.btn_no.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_no.setFont(font)
        self.btn_no.setStyleSheet("QPushButton {\n"
"    background-color: #fefbf6;\n"
"    border: 1.5px solid #e0e0e0;\n"
"    border-radius: 15px;\n"
"    padding: 10px 20px;\n"
"    font-size: 36px;\n"
"    font-weight: bold;\n"
"    color: #333333;\n"
"}")
        self.btn_no.setObjectName("btn_no")
        self.horizontalLayout_2.addWidget(self.btn_no)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.closing_title = QtWidgets.QLabel(widget)
        self.closing_title.setGeometry(QtCore.QRect(10, 90, 350, 50))
        self.closing_title.setMinimumSize(QtCore.QSize(350, 50))
        self.closing_title.setMaximumSize(QtCore.QSize(350, 50))
        font = QtGui.QFont()
        font.setFamily("GangwonEduAll OTF")
        font.setPointSize(36)
        self.closing_title.setFont(font)
        self.closing_title.setAlignment(QtCore.Qt.AlignCenter)
        self.closing_title.setObjectName("closing_title")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.label_date_time.setText(_translate("widget", "2025년 05월 19일 / 22:07분"))
        self.label_current_people.setText(_translate("widget", "현재 재실 인원 : 0명"))
        self.btn_help.setText(_translate("widget", "❓"))
        self.btn_previous_page.setText(_translate("widget", "↩"))
        self.label_main_title.setText(_translate("widget", "문을 완전히 닫으시겠습니까 ?"))
        self.btn_yes.setText(_translate("widget", "네"))
        self.btn_no.setText(_translate("widget", "아니오"))
        self.closing_title.setText(_translate("widget", "문단속🚪(키 관리자 한정)"))
